### ISSUE TITLE
Link to 'plot' page doesn't work when project is not at url root

### ISSUE THREAD

**Issue by dougthor42** [dougthor42/trendlines#33]
# Summary
The link to the `plot` page doens't work when the project is not at the URL root.

# Expected behavior
The link to all pages should work no matter what the base URL is.

# Actual behavior
404: not found

```
The requested URL /plot/example was not found on this server.
```

# Steps to reproduce
On a server with Apache installed:
1. `mkdir /var/www/trendlines`
2. `touch /var/www/trendlines/trendlines.cfg`
3. edit `/etc/apache2/sites-enabled/your-site.conf`:
    ```apache
    <Location /trendlines>
      ProxyPreserveHost On
      ProxyPass http://127.0.0.1:5082/
      ProxyPassReverse http://127.0.0.1:5082/
  
      RequestHeader set X-Forwarded-Port 80
    </Location>
    ```
4. `chown -R www-data:www-data /var/www/trendlines`
5. Make the docker-compose file:
    ```yaml
    # /var/www/trendlines/docker-compose.yml
    version: "3.2"
    services:
      trendlines:
        image: dougthor42/trendlines:latest
        restart: always
        ports:
          - 127.0.0.1:5082:80
        volumes:
          - type: bind
            source: /var/www/trendlines
            target: /data
    ```
6. `docker-compose -f /var/www/trendlines/docker-compose.yml up -d`
7. `service apache2 restart`
8. Add some data
    ```bash
    curl --data '{"metric": "example", "value": 8.616}' \
         --header "Content-Type: application/json" \
         --request POST \
         http://website.url.local/trendlines/api/v1/add
    ```
9. Go to `http://website.url.local/trendlines` in a web browser. See your example metric is listed.
10. Click on the example metric, get 404.

# Possible resolution
Use `url_for` in `index.html`:
```diff
-     var path = "/plot/"
+     var path = "{{ url_for('plot') }}"
