### ISSUE TITLE
Add depends_on to docker-compose files

### ISSUE THREAD

**Issue by dougthor42** [dougthor42/trendlines#99]
I'm not sure if it's needed, but to be on the safe side I should add [`depends_on`](https://docs.docker.com/compose/startup-order/) to the docker-compose files.

```yaml
trendlines:
  depends_on:
    - "celery"
    - "redis"
redis:
celery:
  depends_on:
    - "redis"
```
